---
- hosts: frontend-server
  remote_user: root
  
  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  
#  - name: Install pip
#    apt: name=python-pip state=present

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
  
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  
  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest
  
  - name: Install Docker Module for Python
    pip:
      name: docker

#  - name: Build Docker image from Dockerfile
#    docker_image:
#      name: nginx
#      path: docker
#      state: build

  - name: Running a container NGINX
    docker_container:
      image: nginx
      name: nginx-container
      state: started
      pull: yes
      published_ports:
      ports:
        - "80:80"

  - name: Check if container is running
    shell: docker ps